spring.application.name=capstone

spring.autoconfigure.exclude=org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration

kis.api.url=https://openapi.koreainvestment.com:9443

spring.config.import=application-secret.properties